# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [38]:
a = np.random.random((2,3,5))

In [ ]:
a1 = np.array((6,6))

In [ ]:
# Method 3

#### 4. Print *a*.


In [39]:
print (a)

[[[0.50946398 0.62177477 0.53240022 0.80068999 0.49729126]
  [0.2711557  0.83087116 0.41806446 0.66328216 0.92568766]
  [0.64077971 0.48851235 0.52790675 0.29197753 0.78967211]]

 [[0.3116916  0.64621744 0.71610253 0.10772632 0.33339829]
  [0.52612297 0.13111035 0.65984261 0.85126451 0.2534137 ]
  [0.31191206 0.15375813 0.3495539  0.73958819 0.14624392]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [40]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [41]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [42]:
print (a.size)
print (b.size)
if a.size == b.size:
    print ("¿Are a and b the same size?:",True,"\nThe total number of elements in both of them is:",a.size)
else: 
    print (False)

30
30
¿Are a and b the same size?: True 
The total number of elements in both of them is: 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [47]:
 sumab = a+b
# It cannot be added since a and b have different shapes. 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [48]:
c = b.transpose(1,2,0)
print (c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [64]:
d = a+c

d = print(np.add(a, c))

[[[1.50946398 1.62177477 1.53240022 1.80068999 1.49729126]
  [1.2711557  1.83087116 1.41806446 1.66328216 1.92568766]
  [1.64077971 1.48851235 1.52790675 1.29197753 1.78967211]]

 [[1.3116916  1.64621744 1.71610253 1.10772632 1.33339829]
  [1.52612297 1.13111035 1.65984261 1.85126451 1.2534137 ]
  [1.31191206 1.15375813 1.3495539  1.73958819 1.14624392]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
print ("Matrix a=\n\n",a)
print ("\n")
print ("Matrix d=\n\n",d)
print ("\n")

Matrix a=

 [[[0.50946398 0.62177477 0.53240022 0.80068999 0.49729126]
  [0.2711557  0.83087116 0.41806446 0.66328216 0.92568766]
  [0.64077971 0.48851235 0.52790675 0.29197753 0.78967211]]

 [[0.3116916  0.64621744 0.71610253 0.10772632 0.33339829]
  [0.52612297 0.13111035 0.65984261 0.85126451 0.2534137 ]
  [0.31191206 0.15375813 0.3495539  0.73958819 0.14624392]]]


Matrix d=

 [[[1.50946398 1.62177477 1.53240022 1.80068999 1.49729126]
  [1.2711557  1.83087116 1.41806446 1.66328216 1.92568766]
  [1.64077971 1.48851235 1.52790675 1.29197753 1.78967211]]

 [[1.3116916  1.64621744 1.71610253 1.10772632 1.33339829]
  [1.52612297 1.13111035 1.65984261 1.85126451 1.2534137 ]
  [1.31191206 1.15375813 1.3495539  1.73958819 1.14624392]]]




#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [58]:
#Method 1
#e = a * c
#print (e)

#or

#Method 2
e = print(np.multiply(a, c))

[[[0.50946398 0.62177477 0.53240022 0.80068999 0.49729126]
  [0.2711557  0.83087116 0.41806446 0.66328216 0.92568766]
  [0.64077971 0.48851235 0.52790675 0.29197753 0.78967211]]

 [[0.3116916  0.64621744 0.71610253 0.10772632 0.33339829]
  [0.52612297 0.13111035 0.65984261 0.85126451 0.2534137 ]
  [0.31191206 0.15375813 0.3495539  0.73958819 0.14624392]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [54]:
print ("print a:\n",a,"\n")
print ("print e:\n",e,"\n")
if a.shape == e.shape and a.size == e.size:
    print ("a and e are equal")
    print ("their shape is:",e.shape)
    print ("their size is:",a.size)
           
else:
    print ("a and e are not equal")


print a:
 [[[0.50946398 0.62177477 0.53240022 0.80068999 0.49729126]
  [0.2711557  0.83087116 0.41806446 0.66328216 0.92568766]
  [0.64077971 0.48851235 0.52790675 0.29197753 0.78967211]]

 [[0.3116916  0.64621744 0.71610253 0.10772632 0.33339829]
  [0.52612297 0.13111035 0.65984261 0.85126451 0.2534137 ]
  [0.31191206 0.15375813 0.3495539  0.73958819 0.14624392]]] 

print e:
 [[[0.50946398 0.62177477 0.53240022 0.80068999 0.49729126]
  [0.2711557  0.83087116 0.41806446 0.66328216 0.92568766]
  [0.64077971 0.48851235 0.52790675 0.29197753 0.78967211]]

 [[0.3116916  0.64621744 0.71610253 0.10772632 0.33339829]
  [0.52612297 0.13111035 0.65984261 0.85126451 0.2534137 ]
  [0.31191206 0.15375813 0.3495539  0.73958819 0.14624392]]] 

a and e are equal
their shape is: (2, 3, 5)
their size is: 30


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [65]:
d_max = d.max()
print ("The maximun value of array d is:",d_max)
d_min = d.min()
print ("The minimun value of array d is:", d_min)

AttributeError: 'NoneType' object has no attribute 'max'

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.