# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

In [4]:
a1 = np.empty([2,3,5], dtype=int)

In [5]:
# Method 3

#### 4. Print *a*.


In [5]:
print ("print a with method 1:\n",a)
print ("\n")
print ("print a with method 2:\n",a1)
print ("\n")

print a with method 1:
 [[[0.79119413 0.31688801 0.62615817 0.79315561 0.31437676]
  [0.25640352 0.6500279  0.65277144 0.08805702 0.4010542 ]
  [0.56648601 0.94272585 0.67925456 0.93875006 0.48950462]]

 [[0.42328481 0.77765106 0.37664629 0.25057456 0.44145379]
  [0.95024643 0.87572167 0.6583767  0.32110094 0.60865399]
  [0.59976601 0.85002914 0.170552   0.15633245 0.45458977]]]


print a with method 2:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]




#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [7]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
print (a.size)
print (b.size)
if a.size == b.size:
    print ("¿Are a and b the same size?:",True,"\nThe total number of elements in both of them is:",a.size)
else: 
    print (False)

30
30
¿Are a and b the same size?: True 
The total number of elements in both of them is: 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
sumab = a+b
# It cannot be added since a and b have different shapes. 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [10]:
c = b.transpose(1,2,0)
print (c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [11]:
#Method1
#d = a+c
#print (d)

#Method2
d = np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [12]:
print ("Matrix a=\n\n",a)
print ("\n")
print ("Matrix d=\n\n",d)
print ("\n")

Matrix a=

 [[[0.79119413 0.31688801 0.62615817 0.79315561 0.31437676]
  [0.25640352 0.6500279  0.65277144 0.08805702 0.4010542 ]
  [0.56648601 0.94272585 0.67925456 0.93875006 0.48950462]]

 [[0.42328481 0.77765106 0.37664629 0.25057456 0.44145379]
  [0.95024643 0.87572167 0.6583767  0.32110094 0.60865399]
  [0.59976601 0.85002914 0.170552   0.15633245 0.45458977]]]


Matrix d=

 [[[1.79119413 1.31688801 1.62615817 1.79315561 1.31437676]
  [1.25640352 1.6500279  1.65277144 1.08805702 1.4010542 ]
  [1.56648601 1.94272585 1.67925456 1.93875006 1.48950462]]

 [[1.42328481 1.77765106 1.37664629 1.25057456 1.44145379]
  [1.95024643 1.87572167 1.6583767  1.32110094 1.60865399]
  [1.59976601 1.85002914 1.170552   1.15633245 1.45458977]]]




#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [13]:
#Method 1
#e = a * c
#print (e)

#or

#Method 2
e = np.multiply(a, c)

#### 13. Does *e* equal to *a*? Why or why not?


In [14]:
print ("print a:\n",a,"\n")
print ("print e:\n",e,"\n")
if a.shape == e.shape and a.size == e.size:
    print ("a and e are equal")
    print ("their shape is:",e.shape)
    print ("their size is:",a.size)
           
else:
    print ("a and e are not equal")
    

print a:
 [[[0.79119413 0.31688801 0.62615817 0.79315561 0.31437676]
  [0.25640352 0.6500279  0.65277144 0.08805702 0.4010542 ]
  [0.56648601 0.94272585 0.67925456 0.93875006 0.48950462]]

 [[0.42328481 0.77765106 0.37664629 0.25057456 0.44145379]
  [0.95024643 0.87572167 0.6583767  0.32110094 0.60865399]
  [0.59976601 0.85002914 0.170552   0.15633245 0.45458977]]] 

print e:
 [[[0.79119413 0.31688801 0.62615817 0.79315561 0.31437676]
  [0.25640352 0.6500279  0.65277144 0.08805702 0.4010542 ]
  [0.56648601 0.94272585 0.67925456 0.93875006 0.48950462]]

 [[0.42328481 0.77765106 0.37664629 0.25057456 0.44145379]
  [0.95024643 0.87572167 0.6583767  0.32110094 0.60865399]
  [0.59976601 0.85002914 0.170552   0.15633245 0.45458977]]] 

a and e are equal
their shape is: (2, 3, 5)
their size is: 30


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [15]:
d_max = d.max()
print ("The maximun value of array d is:",d_max)
d_min = d.min()
print ("The minimun value of array d is:", d_min)
d_mean = np.mean(d)
print ("The mean value of array d is:", d_mean)

The maximun value of array d is: 1.950246432390669
The minimun value of array d is: 1.0880570204994084
The mean value of array d is: 1.5473929151125825


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [16]:
f = np.empty([2,3,5], dtype=int)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
reshape_d = d.reshape(30)
new_d = []
for i in reshape_d:
    if i > d_min and i < d_mean:
        new_d.append(25.)
    elif i == d.mean:
        new_d.append(50.)
    elif i > d_mean and i < d_max:
        new_d.append(75.)
    elif i == d.min:
        new_d.append(100.)
    else: 
        new_d.append(0)
array_d = np.array(new_d)
f = array_d.reshape(2,3,5)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
print ("print a:\n",a,"\n")
print ("print f:\n",f,"\n")

print a:
 [[[0.79119413 0.31688801 0.62615817 0.79315561 0.31437676]
  [0.25640352 0.6500279  0.65277144 0.08805702 0.4010542 ]
  [0.56648601 0.94272585 0.67925456 0.93875006 0.48950462]]

 [[0.42328481 0.77765106 0.37664629 0.25057456 0.44145379]
  [0.95024643 0.87572167 0.6583767  0.32110094 0.60865399]
  [0.59976601 0.85002914 0.170552   0.15633245 0.45458977]]] 

print f:
 [[[75. 25. 75. 75. 25.]
  [25. 75. 75.  0. 25.]
  [75. 75. 75. 75. 25.]]

 [[25. 75. 25. 25. 25.]
  [ 0. 75. 75. 25. 75.]
  [75. 75. 25. 25. 25.]]] 



#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
reshape_d = d.reshape(30)
new_d = []
for i in reshape_d:
    if i > d_min and i < d_mean:
        new_d.append("B")
    elif i == d.mean:
        new_d.append("C")
    elif i > d_mean and i < d_max:
        new_d.append("D")
    elif i == d.min:
        new_d.append("E")
    else: 
        new_d.append("A")
array_d = np.array(new_d)
bonus = array_d.reshape(2,3,5)

In [21]:
print (bonus)

[[['D' 'B' 'D' 'D' 'B']
  ['B' 'D' 'D' 'A' 'B']
  ['D' 'D' 'D' 'D' 'B']]

 [['B' 'D' 'B' 'B' 'B']
  ['A' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']]]
