# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
#your code here
import numpy as np


#### 2. Print your NumPy version.

In [2]:
#your code here
print(np.__version__)


1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
#your code here

#Method 1
a = np.random.random((2,3,5))
print ("print a with method 1:\n\n",a)
print ("\n")


print a with method 1:

 [[[0.59618351 0.35974153 0.13372083 0.44610441 0.72666858]
  [0.3100121  0.39278694 0.09494036 0.93244742 0.55045195]
  [0.75842489 0.81853919 0.36111903 0.08834256 0.85080305]]

 [[0.79507328 0.24295486 0.01406228 0.5317246  0.12592669]
  [0.8663842  0.71848899 0.27081539 0.75544182 0.08085881]
  [0.5695428  0.9279654  0.23993457 0.76573692 0.78562125]]]




In [4]:
#your code here

# Method 2
a1 = np.random.randint(0,100,(2,3,5))
print ("print a with method 2:\n\n",a1)
print ("\n")


print a with method 2:

 [[[97 92 14 57 97]
  [17 77 83 77 80]
  [31 31 23 51 42]]

 [[55  9 99 89 95]
  [31 73 25 77 85]
  [48  7 10 66 17]]]




In [5]:
#your code here

# Method 3
a2 = np.random.randn(2,3,5)
print ("print a with method 3:\n\n",a2)
print ("\n")


print a with method 3:

 [[[-0.42063892  0.06822912  0.31144554 -0.78172444  0.92410407]
  [-1.22648832  0.07103621 -1.29531907 -0.50084482  0.31652145]
  [-0.05175892  0.19427725 -0.28782231 -0.7855493  -0.31182202]]

 [[-0.34596475 -0.11977247 -1.45786686  0.39021269  0.14139125]
  [-1.65697184  0.17060937  1.44784435  0.12711308  1.08699358]
  [-0.05932101 -1.14734884 -0.80666679  0.52294765  0.1522837 ]]]




#### 4. Print *a*.


In [6]:
#your code here
# I will use the array a generated in method 1 
print ("print a:\n\n",a)
print ("\n")


print a:

 [[[0.59618351 0.35974153 0.13372083 0.44610441 0.72666858]
  [0.3100121  0.39278694 0.09494036 0.93244742 0.55045195]
  [0.75842489 0.81853919 0.36111903 0.08834256 0.85080305]]

 [[0.79507328 0.24295486 0.01406228 0.5317246  0.12592669]
  [0.8663842  0.71848899 0.27081539 0.75544182 0.08085881]
  [0.5695428  0.9279654  0.23993457 0.76573692 0.78562125]]]




#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
#your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [8]:
#your code here
print("b:\n\n",b)


b:

 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
#your code here

print (a.size)
print (b.size)
if a.size == b.size:
    print ("¿Are a and b the same size?:",True,"\nThe total number of elements in both of them is:",a.size)
else: 
    print (False)
    

30
30
¿Are a and b the same size?: True 
The total number of elements in both of them is: 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
#your answer here
# 3sumab = a+b
# It cannot be added since a and b have different shapes and it wouldnt make mathematical sense to add them. 


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
#your code here
c = b.transpose(1,2,0)
print ("c:\n\n",c)


c:

 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
#Your code here

#Method1
#d = a+c
#print (d)

#Method2
d = np.add(a, c)

#it works now because C and A have the same shape. 


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
#your code here
print ("Matrix a=\n\n",a)
print ("\n")
print ("Matrix d=\n\n",d)
print ("\n")

#They have the same shape and size, but all the values of "d" are greater than the values of "a" by 1.


Matrix a=

 [[[0.59618351 0.35974153 0.13372083 0.44610441 0.72666858]
  [0.3100121  0.39278694 0.09494036 0.93244742 0.55045195]
  [0.75842489 0.81853919 0.36111903 0.08834256 0.85080305]]

 [[0.79507328 0.24295486 0.01406228 0.5317246  0.12592669]
  [0.8663842  0.71848899 0.27081539 0.75544182 0.08085881]
  [0.5695428  0.9279654  0.23993457 0.76573692 0.78562125]]]


Matrix d=

 [[[1.59618351 1.35974153 1.13372083 1.44610441 1.72666858]
  [1.3100121  1.39278694 1.09494036 1.93244742 1.55045195]
  [1.75842489 1.81853919 1.36111903 1.08834256 1.85080305]]

 [[1.79507328 1.24295486 1.01406228 1.5317246  1.12592669]
  [1.8663842  1.71848899 1.27081539 1.75544182 1.08085881]
  [1.5695428  1.9279654  1.23993457 1.76573692 1.78562125]]]




#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
#your code here

#Method 1
#e = a * c
#print (e)

#or

#Method 2
e = np.multiply(a, c)


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
#your code here

print ("print a:\n\n",a,"\n")
print ("print e:\n\n",e,"\n")
if a.shape == e.shape and a.size == e.size:
    print ("a and e are equal")
    print ("their shape is:",e.shape)
    print ("their size is:",a.size)
           
else:
    print ("a and e are not equal")
    
#They are equal, as all the elements of "a" were multipled by 1 to create array "e".  
    

print a:

 [[[0.59618351 0.35974153 0.13372083 0.44610441 0.72666858]
  [0.3100121  0.39278694 0.09494036 0.93244742 0.55045195]
  [0.75842489 0.81853919 0.36111903 0.08834256 0.85080305]]

 [[0.79507328 0.24295486 0.01406228 0.5317246  0.12592669]
  [0.8663842  0.71848899 0.27081539 0.75544182 0.08085881]
  [0.5695428  0.9279654  0.23993457 0.76573692 0.78562125]]] 

print e:

 [[[0.59618351 0.35974153 0.13372083 0.44610441 0.72666858]
  [0.3100121  0.39278694 0.09494036 0.93244742 0.55045195]
  [0.75842489 0.81853919 0.36111903 0.08834256 0.85080305]]

 [[0.79507328 0.24295486 0.01406228 0.5317246  0.12592669]
  [0.8663842  0.71848899 0.27081539 0.75544182 0.08085881]
  [0.5695428  0.9279654  0.23993457 0.76573692 0.78562125]]] 

a and e are equal
their shape is: (2, 3, 5)
their size is: 30


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
#your code here

d_max = d.max()
print ("The maximun value of array d is:",d_max)
d_min = d.min()
print ("The minimun value of array d is:", d_min)
d_mean = np.mean(d)
print ("The mean value of array d is:", d_mean)


The maximun value of array d is: 1.9324474170796728
The minimun value of array d is: 1.0140622786001319
The mean value of array d is: 1.5036939406785508


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
#your code here
f = np.empty([2,3,5], dtype=int)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
#your code here

reshape_d = d.reshape(30)
new_d = []
for i in reshape_d:
    if i > d_min and i < d_mean:
        new_d.append(25.)
    elif i == d_mean:
        new_d.append(50.)
    elif i > d_mean and i < d_max:
        new_d.append(75.)
    elif i == d_max:
        new_d.append(100.)
    else: 
        new_d.append(0.)
array_d = np.array(new_d)
f = array_d.reshape(2,3,5)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
#your code here
print ("print a:\n",a,"\n")
print ("print f:\n",f,"\n")


print a:
 [[[0.59618351 0.35974153 0.13372083 0.44610441 0.72666858]
  [0.3100121  0.39278694 0.09494036 0.93244742 0.55045195]
  [0.75842489 0.81853919 0.36111903 0.08834256 0.85080305]]

 [[0.79507328 0.24295486 0.01406228 0.5317246  0.12592669]
  [0.8663842  0.71848899 0.27081539 0.75544182 0.08085881]
  [0.5695428  0.9279654  0.23993457 0.76573692 0.78562125]]] 

print f:
 [[[ 75.  25.  25.  25.  75.]
  [ 25.  25.  25. 100.  75.]
  [ 75.  75.  25.  25.  75.]]

 [[ 75.  25.   0.  75.  25.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]]] 



#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
#your code here

reshape_d = d.reshape(30)
new_d = []
for i in reshape_d:
    if i > d_min and i < d_mean:
        new_d.append("B")
    elif i == d_mean:
        new_d.append("C")
    elif i > d_mean and i < d_max:
        new_d.append("D")
    elif i == d_max:
        new_d.append("E")
    else: 
        new_d.append("A")
array_d = np.array(new_d)
bonus = array_d.reshape(2,3,5)


In [21]:
#your code here
print (bonus)


[[['D' 'B' 'B' 'B' 'D']
  ['B' 'B' 'B' 'E' 'D']
  ['D' 'D' 'B' 'B' 'D']]

 [['D' 'B' 'A' 'D' 'B']
  ['D' 'D' 'B' 'D' 'B']
  ['D' 'D' 'B' 'D' 'D']]]
